[package]
name = "ineff_prover"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.5.0"
ark-ec = {version="0.5.0" ,features = ["parallel"]}
ark-ff =  {version="0.5.0" ,features = ["parallel"]}
ark-poly = "0.5.0"
ark-std = "0.5.0"
rayon = "1.10.0"
sha2 = "0.10.8"





